### ISSUE TITLE
java.nio.channels.UnresolvedAddressException?

### ISSUE THREAD

**Issue by benni82** [apache-spark-on-k8s/kubernetes-HDFS#28]
a datanode logs
```
17/11/22 11:22:43 INFO datanode.DataNode: DatanodeRegistration(10.218.137.87:50010, datanodeUuid=f0b95cda-a2af-4758-8078-dcf7d6427753, infoPort=50075, infoSecurePort=0, ipcPort=50020, storageInfo=lv=-56;cid=CID-55bc32d0-2b9e-4a59-9094-5d364bf60743;nsid=1425006603;c=0) Starting thread to transfer BP-2130985803-10.125.4.206-1510718548982:blk_1073741870_1046 to 10.125.4.206:50010 10.218.137.142:50010
Exception in thread "org.apache.hadoop.hdfs.server.datanode.DataNode$DataTransfer@1404b2f4" java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:192)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:495)
	at org.apache.hadoop.hdfs.server.datanode.DataNode$DataTransfer.run(DataNode.java:2087)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "org.apache.hadoop.hdfs.server.datanode.DataNode$DataTransfer@2ca203a0" java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:192)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:495)
	at org.apache.hadoop.hdfs.server.datanode.DataNode$DataTransfer.run(DataNode.java:2087)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Anshuamrita** [comment]
Even I am facing similar issue which is mentioned above. In my case there are two pods in cluster which try to communicate each other.But when pod1 tries to reach pod2 it says :+1: Could not connect to <podname> following to which UnresovedAddressException is thrown.
Also I am specifying service name to resolve, but somehow pod name is going there.
Please guide me or suggest workaround

**Comment by StanislavKo** [comment]
Hello, it's needed to set "dfs.datanode.use.datanode.hostname" property in "/etc/hadoop/hdfs-site.xml" file to "false"
