### ISSUE TITLE
Error when running on Minikube

### ISSUE THREAD

**Issue by pacuna** [apache-spark-on-k8s/kubernetes-HDFS#67]
I'm trying to run the most simple hdfs version on Minikube. I'm trying using this:

```
# label the node
 kubectl label nodes minikube hdfs-namenode-selector=hdfs-namenode-0
```

And then

```
helm install -n my-hdfs charts/hdfs-k8s  \
      --set tags.ha=false  \
      --set tags.simple=true  \
      --set global.namenodeHAEnabled=false  \
      --set hdfs-simple-namenode-k8s.nodeSelector.hdfs-namenode-selector=hdfs-namenode-0
```
But the namenode won't start:

```
NAME                                   READY   STATUS             RESTARTS   AGE
my-hdfs-client-564fcddf6d-88j4w        1/1     Running            0          4m29s
my-hdfs-datanode-h7lrc                 0/1     Running            2          4m29s
my-hdfs-namenode-0                     0/1     CrashLoopBackOff   5          4m29s
```

And the logs for the pod show this:

```
...
19/04/05 16:08:54 INFO ipc.Server: Stopping server on 8020
19/04/05 16:08:54 INFO namenode.FSNamesystem: Stopping services started for active state
19/04/05 16:08:54 INFO namenode.FSNamesystem: Stopping services started for standby state
19/04/05 16:08:54 INFO mortbay.log: Stopped HttpServer2$SelectChannelConnectorWithSafeStartup@0.0.0.0:50070
19/04/05 16:08:54 INFO impl.MetricsSystemImpl: Stopping NameNode metrics system...
19/04/05 16:08:54 INFO impl.MetricsSystemImpl: NameNode metrics system stopped.
19/04/05 16:08:54 INFO impl.MetricsSystemImpl: NameNode metrics system shutdown complete.
19/04/05 16:08:54 ERROR namenode.NameNode: Failed to start namenode.
java.io.IOException: Could not parse line: rootfs                   0     0         0        - /hadoop/dfs/name
	at org.apache.hadoop.fs.DF.parseOutput(DF.java:197)
	at org.apache.hadoop.fs.DF.getFilesystem(DF.java:78)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeResourceChecker$CheckedVolume.<init>(NameNodeResourceChecker.java:69)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeResourceChecker.addDirToCheck(NameNodeResourceChecker.java:165)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeResourceChecker.<init>(NameNodeResourceChecker.java:134)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startCommonServices(FSNamesystem.java:1058)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.startCommonServices(NameNode.java:678)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:664)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:811)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:795)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1488)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1554)
19/04/05 16:08:54 INFO util.ExitUtil: Exiting with status 1
19/04/05 16:08:54 INFO namenode.NameNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at minikube/127.0.1.1
```

Any ideas? 

Thanks.

**Comment by pacuna** [comment]
I think it's some kind of permission issue with the volume. I remove the volume part from the chart and the pod starts correctly.
