### ISSUE TITLE
Unable to benchmark hadoop on k8s-cluster

### ISSUE THREAD

**Issue by shashank855** [apache-spark-on-k8s/kubernetes-HDFS#76]
- I have deployed HDFS on k8s-cluster following the HDFS repo readme. I have used **OpenEBS** for the HDFS volumes. All components are running fine. 
- Now I want to benchmark hdfs. I tried using **TeraGen**, I exec inside hdfs client pod, went to path `/opt/hadoop-2.7.2/share/hadoop/hdfs` and run this command: `hadoop jar hadoop-hdfs-2.7.2-tests.jar TestDFSIO -write -nrFiles 1 -fileSize 1000` . But it didn't worked and the folowing output.
```
root@my-hdfs-client-544d894fc7-vnljw:/opt/hadoop-2.7.2/share/hadoop/hdfs# hadoop jar hadoop-hdfs-2.7.2.jar TestDFSIO -write -nrFiles 1 -fileSize 1000
Exception in thread "main" java.lang.ClassNotFoundException: TestDFSIO
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:214)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
```
 I don't khow how to proceed. I didn't found any steps or reference docs on the official github repo.

**Comment by thucnd55** [comment]
Hello shashank855  .
How about Benchmark hdfs on K8s now ? I'm try to benchmark it ...
